---
apiVersion: v1
kind: ConfigMap
metadata:
  name: colossus-grafana-provisioning
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: colossus-grafana
    app.kubernetes.io/component: provisioning
    metrics_scrape_enabled: "true"
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://vmsingle-colossus.monitoring.svc:8428
        isDefault: true
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://vlsingle-colossus.monitoring.svc:9428
  dashboards.yaml: |
    apiVersion: 1

    providers:
      - name: Prometheus
        orgId: 1
        folder: ''
        type: file
        options:
          path: /opt/git/link/colossus/monitoring/dashboards
