---
apiVersion: v1
kind: ConfigMap
metadata:
  name: colossus-grafana-git
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: colossus-grafana
    app.kubernetes.io/component: dashboards-git
    metrics_scrape_enabled: "true"
data:
  GITSYNC_REPO: "https://github.com/ojgenbar/Colossus.git"
  GITSYNC_REF: "main"
  GITSYNC_PERIOD: "1h"
