---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vlagent-colossus
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vlagent-colossus
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vlagent-colossus
subjects:
  - kind: ServiceAccount
    name: vlagent-colossus
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: vlagent-colossus
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: operator.victoriametrics.com/v1
kind: VLAgent
metadata:
  name: colossus
  namespace: monitoring
spec:
  serviceAccountName: vlagent-colossus
  useStrictSecurity: true
  k8sCollector:
    enabled: true
  remoteWrite:
    - url: "http://vlsingle-colossus.monitoring.svc:9428/insert/native"
