apiVersion: v1
kind: Service
metadata:
  name: colossus-ui
  namespace: default
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: colossus-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: colossus-ui

---

apiVersion: v1
kind: Service
metadata:
  name: colossus-ui-nodeport
  namespace: default
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: colossus-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30002
  selector:
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: colossus-ui
